spring:
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: postgres
    driver-class-name: com.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.hibernate.SQL: debug
