spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/db_springboot_cloud?serverTimezone=Europe/Madrid
#    url: jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&userSSL=false
    username: rabad
    password: rabadrabad
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: debug